type: object
additionalProperties: false
require: [ buckets ]
properties:
  buckets:
    description: >
      List of buckets specified using this mixin bucket schema.
    type: array
    items: {$ref: "#/definitions/bucket"}
    minItems: 1

  tags:
    description: >
      Optional tags attached to your buckets to make it easier to track and monitor.
    type: object
